# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.input.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import image_rc, sys

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1087, 749)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 1101, 751))
        self.widget.setStyleSheet("\n"
"background-color: rgb(243, 243, 243);")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 1091, 81))
        self.widget_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_2.setObjectName("widget_2")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(700, 30, 191, 31))
        self.label_5.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(920, 30, 111, 31))
        self.label_6.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(570, 30, 91, 31))
        self.label_7.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(10, 17, 91, 41))
        self.label_8.setStyleSheet("image: url(:/newPrefix/Downloads/KM.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setGeometry(QtCore.QRect(0, 10, 191, 61))
        self.label_10.setStyleSheet("image: url(:/img/1-removebg-preview.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(30, 110, 1041, 561))
        self.widget_3.setStyleSheet("background-color: rgb(241, 241, 241);")
        self.widget_3.setObjectName("widget_3")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setGeometry(QtCore.QRect(10, 10, 271, 31))
        self.label.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 51, 21))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.jjj = QtWidgets.QLineEdit(self.widget_3)
        self.jjj.setGeometry(QtCore.QRect(30, 120, 961, 61))
        self.jjj.setAccessibleName("")
        self.jjj.setStyleSheet("border:none;\n"
"border-bottom: 1px solid;")
        self.jjj.setInputMask("")
        self.jjj.setText("")
        self.jjj.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.jjj.setClearButtonEnabled(True)
        self.jjj.setObjectName("jjj")
        self.jjj_2 = QtWidgets.QLineEdit(self.widget_3)
        self.jjj_2.setGeometry(QtCore.QRect(30, 280, 961, 61))
        self.jjj_2.setAccessibleName("")
        self.jjj_2.setStyleSheet("border:none;\n"
"border-bottom: 1px solid;")
        self.jjj_2.setInputMask("")
        self.jjj_2.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.jjj_2.setClearButtonEnabled(True)
        self.jjj_2.setObjectName("jjj_2")
        self.jjj_3 = QtWidgets.QLineEdit(self.widget_3)
        self.jjj_3.setGeometry(QtCore.QRect(30, 450, 961, 61))
        self.jjj_3.setAccessibleName("")
        self.jjj_3.setStyleSheet("border:none;\n"
"border-bottom: 1px solid;")
        self.jjj_3.setInputMask("")
        self.jjj_3.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.jjj_3.setClearButtonEnabled(True)
        self.jjj_3.setObjectName("jjj_3")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(30, 260, 51, 21))
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setGeometry(QtCore.QRect(30, 440, 81, 21))
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(450, 700, 191, 31))
        self.pushButton.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(780, 720, 291, 21))
        self.label_9.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(-11, -1, 601, 331))
        self.frame.setStyleSheet("background-color: rgb(3, 3, 3);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.widget.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Pendaftaran Akun"))
        self.label_6.setText(_translate("Form", "Informasi"))
        self.label_7.setText(_translate("Form", "Program"))
        self.label.setText(_translate("Form", "Pendaftaran Akun"))
        self.label_2.setText(_translate("Form", "Nama"))
        self.jjj.setAccessibleDescription(_translate("Form", "jj"))
        self.jjj.setPlaceholderText(_translate("Form", "Nama Lengkap"))
        self.jjj_2.setAccessibleDescription(_translate("Form", "jj"))
        self.jjj_2.setText(_translate("Form", "Email"))
        self.jjj_2.setPlaceholderText(_translate("Form", "Nama Lengkap"))
        self.jjj_3.setAccessibleDescription(_translate("Form", "jj"))
        self.jjj_3.setText(_translate("Form", "Password"))
        self.jjj_3.setPlaceholderText(_translate("Form", "Nama Lengkap"))
        self.label_3.setText(_translate("Form", "Email"))
        self.label_4.setText(_translate("Form", "Password"))
        self.pushButton.setText(_translate("Form", "Selanjutnya"))
        self.label_9.setText(_translate("Form", "Developer by Hendra Saputra Philippus"))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
